using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class LevelManager : MonoBehaviour {

	public float waitToRespawn;
	public PlayerController thePlayer;


	// Use this for initialization
	void Start () {
		thePlayer = FindObjectOfType<PlayerController>();

	}
	
	// Update is called once per frame
	void Update () {
		
	}

	public void Respawn()
	{
		StartCoroutine("RespawnCo");

	}

	public IEnumerator RespawnCo()
	{
		thePlayer.gameObject.SetActive(false);

		yield return new WaitForSeconds(waitToRespawn);

		thePlayer.transform.position = thePlayer.respawnPosition;
		thePlayer.gameObject.SetActive(true);
	}
}
